# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  # # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
  # # If you'd like to customize it, uncomment and adjust the pipeline.
  # # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: SpacyNLP
    model: "en_core_web_md"
    case_sensitive: False
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    entity_recognition: False # in this case diet is used only as an intent classifier
    constrain_similarities: True
    model_confidence: linear_norm # without this his default is softmax
  - name: CRFEntityExtractor
  - name: "DucklingEntityExtractor" # extractor used for date and time
    url: "http://localhost:8000"
    dimensions: ["time"]
  - name: "SpacyEntityExtractor" # extractor used for person names
    dimensions: ["PERSON"]
  - name: SklearnIntentClassifier
    #epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: True
    model_confidence: linear_norm # without this his default is softmax
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
# Le Policies sono usate dall’assistente per decidere quale azione intraprendere in ogni fase di una conversazione.
policies:
  # # No configuration for policies was provided. The following default policies were used to train your model.
  # # If you'd like to customize them, uncomment and adjust the policies.
  # # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5 # This controls how much dialogue history the model looks at to decide which action to take next
    epochs: 100
    constrain_similarities: True
    model_confidence: linear_norm
  - name: RulePolicy
